/**
 * Hardcoded parts master seed — used when FINAL.xlsx is not in the repo.
 * Material codes match names generated by the inventory Excel parser.
 */

import { DEFAULT_HSN_CODE } from "@/lib/po-gst";
import type { PartMaster } from "@/lib/types";

type SeedPart = Omit<PartMaster, "isActive">;

function kent(
  itemCode: string,
  description: string,
  weightGrams: number,
  materialCode: string,
  scrapPercent = 8,
  defaultHsnCode = DEFAULT_HSN_CODE
): SeedPart {
  return {
    itemCode,
    description,
    customerCode: "KENT",
    customerName: "Kent RO Systems",
    weightGrams,
    materialCode,
    scrapPercent,
    defaultHsnCode,
  };
}

function part(
  itemCode: string,
  description: string,
  customerCode: string,
  customerName: string,
  weightGrams: number,
  materialCode: string,
  scrapPercent = 8,
  defaultHsnCode = DEFAULT_HSN_CODE
): SeedPart {
  return {
    itemCode,
    description,
    customerCode,
    customerName,
    weightGrams,
    materialCode,
    scrapPercent,
    defaultHsnCode,
  };
}

/** ~65 Kent RO parts + a handful for BMR / Prem / Haier / Veira. */
export const SEED_PARTS: SeedPart[] = [
  // —— Kent RO (65) ——
  kent("KEN001", "Front Panel White Grand Plus", 185, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN002", "Front Panel White Zenith", 172, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN003", "Front Panel White Pearl", 160, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN004", "Side Panel LH White", 95, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN005", "Side Panel RH White", 95, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN006", "Top Cover White UVS", 110, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN007", "Bottom Base White", 220, "ABS_KENT_WHITE_UVS_120"),
  kent("KEN008", "Tank Cover Transparent", 85, "TOYLAC_555_ABS_TRANSPARENT"),
  kent("KEN009", "Sight Glass Cover", 45, "TOYLAC_555_ABS_TRANSPARENT"),
  kent("KEN010", "Filter Housing Clear", 120, "TOYLAC_555_ABS_TRANSPARENT"),
  kent("KEN011", "Display Bezel Black", 38, "SU_JET_BLACK_KENT_BLACK_"),
  kent("KEN012", "Control Knob Black", 12, "SU_JET_BLACK_KENT_BLACK_"),
  kent("KEN013", "Rear Cover Black", 145, "SU_JET_BLACK_KENT_BLACK_"),
  kent("KEN014", "Foot Pad Set Black", 28, "SU_JET_BLACK_KENT_BLACK_"),
  kent("KEN015", "Tank Tray Grand Star", 45, "HIPS_SH03", 8, "842199"),
  kent("KEN016", "Tank Tray Zenith RO", 42, "HIPS_SH03", 8, "842199"),
  kent("KEN017", "Tank Tray Pearl Star", 40, "HIPS_SH03", 8, "842199"),
  kent("KEN018", "Drip Tray White HIPS", 55, "HIPS_SH03", 8, "842199"),
  kent("KEN019", "Inner Liner Natural", 310, "HIPS_SH03"),
  kent("KEN020", "Storage Tank Outer HIPS", 280, "HIPS_SH03"),
  kent("KEN021", "Valve Cap Natural", 8, "ABS_920", 8, "842199"),
  kent("KEN022", "Spout Adaptor Natural", 15, "ABS_920", 8, "842199"),
  kent("KEN023", "Elbow Fitting Natural", 10, "ABS_920", 8, "842199"),
  kent("KEN024", "Membrane Cap Natural", 18, "ABS_920", 8, "842199"),
  kent("KEN025", "PP Filter Housing Body", 95, "PP_COMPOUND_SEE_SIDE_WHITE", 8, "842199"),
  kent("KEN026", "PP Sediment Cap", 22, "PP_COMPOUND_SEE_SIDE_WHITE", 8, "842199"),
  kent("KEN027", "PP Carbon Cap", 22, "PP_COMPOUND_SEE_SIDE_WHITE", 8, "842199"),
  kent("KEN028", "PP See Side Gray Panel", 130, "PP_COMPOUND_SEE_SIDE_GRAY"),
  kent("KEN029", "PP See Side Gray Cover", 75, "PP_COMPOUND_SEE_SIDE_GRAY"),
  kent("KEN030", "PP B220 Connector", 14, "RELIANCE_PP_B_220"),
  kent("KEN031", "PP B120 Tube Clip", 6, "RELIANCE_PP_B120"),
  kent("KEN032", "PP 2120MC Bracket", 48, "PP_2120MC"),
  kent("KEN033", "PP SRM100 NC Mount", 35, "PP_SRM_100_NC"),
  kent("KEN034", "PP MI3530 Clip", 9, "PP_MI_3530"),
  kent("KEN035", "PP B400 MN Cap", 18, "PP_B_400_MN"),
  kent("KEN036", "ICP IM3120 Handle", 62, "ICP_IM_3120_MA"),
  kent("KEN037", "PPTF Sky Blue Accent", 25, "PPTF_30_SKY_BLUE"),
  kent("KEN038", "ABS 300MFR Frame Insert", 55, "ABS_300MFR"),
  kent("KEN039", "ABS 300 Natural Insert", 50, "ABS_300_NATURAL"),
  kent("KEN040", "PC+ABS Latch Housing", 40, "PC__ABS"),
  kent("KEN041", "PC+ABS Cutting Plate", 70, "PC__ABS_CUTTING"),
  kent("KEN042", "Delrin Pom Latch Pin", 5, "DERLIN_POM_090"),
  kent("KEN043", "Makrolon Lens Cover", 30, "MAKROLON_2407_NATURAL"),
  kent("KEN044", "Calcium Filler Spacer", 20, "CALCIUM_FILLER_5208040_DL108"),
  kent("KEN045", "MB White Accent Cap", 8, "MB11135_WHITE"),
  kent("KEN046", "MB Blue Accent Ring", 4, "418323340BLUE"),
  kent("KEN047", "MB Green Accent Ring", 4, "318322626GREEN"),
  kent("KEN048", "MB Pink Accent Ring", 4, "818357271PINK"),
  kent("KEN049", "MB Brown Accent Knob", 6, "NNCBROWN"),
  kent("KEN050", "MB Jet Black Tint Cap", 7, "PP_BLACK_JET_340"),
  kent("KEN051", "MB 9776 Z Black Tint", 7, "9776_Z_BLACK"),
  kent("KEN052", "MB HIPS 114 Tint Cap", 7, "HIPS_114"),
  kent("KEN053", "MB ABS Golden Accent", 9, "ABS_GOLDEN_7280"),
  kent("KEN054", "MB ABS 3868 Accent", 9, "ABS_3868"),
  kent("KEN055", "MB ABS 8845 Accent", 9, "ABS_8845"),
  kent("KEN056", "MB ABS 1458 Accent", 9, "ABS_1458"),
  kent("KEN057", "MB Smoke Gray Bezel", 11, "SMOKE_GRAY_367"),
  kent("KEN058", "MB Cool Grey Trim", 11, "COOL_GREY_8890"),
  kent("KEN059", "MB Graphite Grey Trim", 11, "GRAPHITE_GRAEY_8958"),
  kent("KEN060", "MB Warm Gray Trim", 11, "WARM_GRAY_8907"),
  kent("KEN061", "MB Dark Gray Trim", 11, "DARK_GRAY_2115741"),
  kent("KEN062", "MB PP Blue Tint Cap", 6, "PP_BLUE"),
  kent("KEN063", "MB PP 101260 Tint", 6, "PP_101260"),
  kent("KEN064", "MB GPPS 239 Tint Cap", 6, "GPPS_239"),
  kent("KEN065", "MB EP/HIPS Blend Cap", 8, "HIPS_114"),
  // Legacy codes from existing Kent fixture POs
  kent("602240", "POWP-TANK TRAY GRAND STAR", 45, "HIPS_SH03", 8, "842199"),
  kent("601351B", "POWP-TANK TRAY ZENITH RO", 42, "HIPS_SH03", 8, "842199"),

  // —— BMR HVAC ——
  part("11009231", "FREEZER FRAME", "BMR", "BMR HVAC", 48.5, "HIPS_SH03"),
  part(
    "11031643",
    "NDC 215 EVA BACK COVER",
    "BMR",
    "BMR HVAC",
    22,
    "PP_COMPOUND_SEE_SIDE_WHITE"
  ),
  part("BMR001", "Freezer Door Liner White", "BMR", "BMR HVAC", 320, "HIPS_SH03"),
  part(
    "BMR002",
    "Evaporator Cover Gray",
    "BMR",
    "BMR HVAC",
    95,
    "PP_COMPOUND_SEE_SIDE_GRAY"
  ),

  // —— Prem ——
  part(
    "84189900",
    "ADJUSTABLE LEG BOTTOM HINGE",
    "PREM",
    "Prem Industries",
    4.2,
    "ABS_920"
  ),
  part(
    "PREM001",
    "Hinge Pin Natural ABS",
    "PREM",
    "Prem Industries",
    3.5,
    "ABS_920"
  ),

  // —— Haier ——
  part(
    "HAI001",
    "Refrigerator Door Cap White",
    "HAIER",
    "Haier",
    55,
    "ABS_KENT_WHITE_UVS_120"
  ),
  part("HAI002", "Shelf Clip Natural", "HAIER", "Haier", 8, "ABS_920"),
  part(
    "HAI003",
    "Crisper Handle Gray",
    "HAIER",
    "Haier",
    28,
    "PP_COMPOUND_SEE_SIDE_GRAY"
  ),

  // —— Veira ——
  part(
    "VEI001",
    "Cooler Top Lid White",
    "VEIRA",
    "Veira",
    210,
    "PP_COMPOUND_SEE_SIDE_WHITE"
  ),
  part(
    "VEI002",
    "Cooler Drain Cap Black",
    "VEIRA",
    "Veira",
    12,
    "SU_JET_BLACK_KENT_BLACK_"
  ),
  part("VEI003", "Cooler Handle ABS", "VEIRA", "Veira", 45, "ABS_300_NATURAL"),
];

export function seedPartsAsMaster(): PartMaster[] {
  return SEED_PARTS.map((p) => ({ ...p, isActive: true }));
}
